name: On Pull Request

env:
  TZ: Asia/Tokyo

on:
  pull_request:
  pull_request_target:

jobs:
  # check_user:
  #   name: Check User
  #   runs-on: ubuntu-22.04
  #   # dependabotならpull_request_target以外を無視
  #   # dependabot以外ならpull_request_targetを無視
  #   # https://engineering.mobalab.net/2021/04/30/make-secrets-available-in-pull-request-opened-by-dependabot/
  #   if: |
  #     (github.event_name == 'pull_request_target' && github.actor != 'redshoga') ||
  #     (github.event_name != 'pull_request_target' && github.actor == 'redshoga')
  #   steps:
  #     - run: echo "completed Check User"
  example:
    # needs: check_user
    name: Example
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # pull_request_target 駆動の場合は HEAD コミットを明示的に指定する必要があるため
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: echo
        run: echo "hello world 3"
      - name: cat
        run: cat sample.txt
        