name: On Pull Request

env:
  TZ: Asia/Tokyo

on:
  pull_request:
  pull_request_target:

jobs:
  example:
    name: Example
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: echo
        run: echo "hello world 1"